### ISSUE TITLE
User Guide suggestions

### ISSUE THREAD

**Issue by andypiper** [dupontgu/dial_toner#3]
- [x] link to it from GitHub
- [x] put the source for it on GitHub so others can submit edits 😄
  - even if it is also published as a Google Doc... there's Markdown support for GDocs now, too...
- [x] add a note on dial positions with an image to show that the numeric indicator is set by the line, with the dot to the left of it.
- [x] add a note on renaming the CIRCUITPY drive if desired?
  - could just be a [link to the Adafruit doc](https://learn.adafruit.com/welcome-to-circuitpython/renaming-circuitpy) for simplicity. I renamed mine DIALTONER (which is conveniently the same length as CIRCUITPY)
- [x] add the upcoming "option 5" configuration option for keyboard emulation type

**Comment by dupontgu** [comment]
Awesome, Andy- thanks! Most of this is already in progress, except for the CIRCUITPY renaming thing. That's a great callout.

**Comment by dupontgu** [comment]
merged in #2! Usage guide found [here](https://github.com/dupontgu/dial_toner/tree/main/basic) now.
